Repository Hackathon-Spring-2024-TeamG/team-g-app, pull requests merged in 2024-05, with the labels that each got.

#45 テーブル構成変更
  ChatApp/app.py
  ChatApp/models.py
  Docker/MySQL/init.sql
Labels: Backend

#54 フロントデザイン修正と個人チャンネル作成・削除機能実装
  ChatApp/app.py
  ChatApp/models.py
  ChatApp/static/img/user_default.png
  ChatApp/static/img/user_default01.png
  ChatApp/static/img/user_default02.png
  ChatApp/templates/account.html
  ChatApp/templates/base.html
  ChatApp/templates/index.html
  ChatApp/templates/list_personal_channels.html
  ChatApp/templates/personal/personal_channels.html
  ChatApp/templates/registration/base.html
  ChatApp/templates/registration/login.html
  ChatApp/templates/registration/signup.html
Labels: Backend, Frontend

#66 個人チャンネル更新機能実装
  ChatApp/app.py
  ChatApp/models.py
  ChatApp/static/js/PersonalChannels/personalChannelUpdateModal.js
  ChatApp/static/js/PersonalChannels/setupDeleteConfirmationModal.js
  ChatApp/templates/base.html
  ChatApp/templates/personal/personal_channels.html
  ChatApp/templates/registration/base.html
Labels: Backend, Frontend

#75 ページネーションの実装
  ChatApp/static/js/pagination.js
  ChatApp/templates/base.html
  ChatApp/templates/index.html
  Docker/MySQL/init.sql
Labels: Frontend

#78 Feature/#20
  ChatApp/app.py
  ChatApp/models.py
  ChatApp/templates/base.html
  ChatApp/templates/detail.html
  ChatApp/templates/index.html
  ChatApp/templates/personal/detail.html
  ChatApp/templates/personal/personal_channels.html
  ChatApp/templates/registration/base.html
  Docker/MySQL/init.sql
Labels: Backend
